spring: 
  application:
    name: microservice-auth-server
server:
  port: 8040
  context-path: /uaa
security:
  sessions: stateless
eureka:
  instance:
    hostname: auth-server
  client:
    serviceUrl: 
      defaultZone: http://discovery:8761/eureka/
      