spring:
  application.name: microservice-hystrix-dashboard
server:
  port: 8060
#security.basic.enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

turbine:
  app-config: microservice-demo,microservice-demo-web
  aggregator:
    clusterConfig: default
    clusterNameExpression: new String("default")
    combine-host: true
    instanceUrlSuffix: 
      default: actuator/hystrix.stream

      
      
