security:
  basic:
    enabled: false
server:
  port: 8040
  session:
    timeout: 300
spring: 
  application:
    name: microservice-auth-server
  datasource:                       
    url: jdbc:mysql://127.0.0.1:3306/microservice_system?useUnicode=true&amp;characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
eureka: 
  instance:
    hostname: auth-server
  client:
    serviceUrl: 
      defaultZone: http://discovery:8761/eureka/