server:
  port: 12000
spring:
  application:
    name: microservice-wemall-order    
  jpa: 
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        dialect : org.hibernate.dialect.MySQL5Dialect
  datasource:                       
    url: jdbc:mysql://127.0.0.1:3306/wemall_springcloud?useUnicode=true&amp;characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root  
    password: root
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    #healthcheck: 
     # enabled: true
    serviceUrl: 
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}