server:
  port: 8050
spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vangyong/wemall-springcloud.git/
          search-paths: config-repo
          username: vangyong
          password: 123456
#        health:
#          repositories:
#            check:
#              name:
#              label: 
#              profiles: prod  
#  rabbitmq:                            
#     addresses: 127.0.0.1:5672
#     username: springcloud
#     password: springcloud
#     virtual-host: /       
eureka:
  instance:
    hostname: config
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/