spring:
  application:
    name: microservice-hystrix-turbine
server:
  port: 8030
#security.basic.enabled: false
turbine:
  aggregator: 
    clusterConfig: default
  appConfig: microservice-demo,microservice-demo-web
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/